@Web_HostAddress = http://localhost:5191

GET {{Web_HostAddress}}/api/movie/
Accept: application/json
###

GET {{Web_HostAddress}}/api/movie/title/tt0108052
Accept: application/json
###

GET {{Web_HostAddress}}/api/movie/comment/tt0108052
Accept: application/json

###

POST {{Web_HostAddress}}/api/movie/
Content-Type: application/json

{
  "title": "El Señor de los Anillos: La Comunidad del Anillo",
  "synopsis": "En un mundo de hobbits, elfos y magos, un joven hobbit llamado Frodo Bolsón hereda el Anillo Único de su tío Bilbo y se embarca en un peligroso viaje para destruirlo en el fuego del Monte del Destino.",
  "year": 2001,
  "duration": 178,
  "genre": "Aventura, fantasía",
  "image": "https://m.media-amazon.com/images/M/MV5BN2EyZjM3NzUtNTIzMi00MjM2LWEwMjktYzI1MjgzNmI4ZjM0XkEyXkFqcGdeQXVyNjU0OTQ0OTY@._V1_UX182_CR0,0,182,268_AL_.jpg"
}
