@Web_HostAddress = http://localhost:5191

GET {{Web_HostAddress}}/api/movie/
Accept: application/json
###

GET {{Web_HostAddress}}/api/movie/10
Accept: application/json
###

POST {{Web_HostAddress}}/api/movie/
Content-Type: application/json

{
  "title": "",
  "synopsis": "El Terminator es un personaje ficticio creado por James Cameron en 1984. Fue diseñado para ser un agente secreto de una organización secreta llamada S.H.I.E.L.D. que busca eliminar a los supervivientes de los asesinatos de personas muertas en el futuro.",
  "year": 1984,
  "duration": 121,
  "genre": "Ficción, ciencia ficción",
  "image": "https://m.media-amazon.com/images/M/MV5BMjA5NjM2ODU0NF5BMl5BanBnXkFtZTgwMDU2MjEyMDE@._V1_UX182_CR0,0,182,268_AL_.jpg"
}
